### ISSUE TITLE
Can't install PHP Debug to VS Code

### ISSUE THREAD

**Issue by chrisbiasbas** [xdebug/vscode-php-debug#304]
Tried to install from VS Code and manually. Failed either way. How do I fix this?

PHP version:  7.1.16
XDebug version:  1.12.5
```
2018-09-08 4:33:18 PM - Microsoft VSIX Installer
2018-09-08 4:33:18 PM - -------------------------------------------
2018-09-08 4:33:18 PM - vsixinstaller.exe version:
2018-09-08 4:33:18 PM - 15.8.3237
2018-09-08 4:33:18 PM - -------------------------------------------
2018-09-08 4:33:18 PM - Command line parameters:
2018-09-08 4:33:18 PM - C:\Program Files (x86)\Microsoft Visual Studio\Installer\resources\app\ServiceHub\Services\Microsoft.VisualStudio.Setup.Service\VSIXInstaller.exe,C:\Users\cbiasbas\Downloads\felixfbecker.php-debug-1.12.5 (1).vsix
2018-09-08 4:33:18 PM - -------------------------------------------
2018-09-08 4:33:18 PM - Microsoft VSIX Installer
2018-09-08 4:33:18 PM - -------------------------------------------
2018-09-08 4:33:19 PM - Initializing Install...
2018-09-08 4:33:19 PM - Extension Details...
2018-09-08 4:33:19 PM - 	Identifier         : php-debug
2018-09-08 4:33:19 PM - 	Name               : PHP Debug
2018-09-08 4:33:19 PM - 	Author             : felixfbecker
2018-09-08 4:33:19 PM - 	Version            : 1.12.5
2018-09-08 4:33:19 PM - 	Description        : Debug support for PHP with XDebug
2018-09-08 4:33:19 PM - 	Locale             : en-US
2018-09-08 4:33:19 PM - 	MoreInfoURL        : 
2018-09-08 4:33:19 PM - 	InstalledByMSI     : False
2018-09-08 4:33:19 PM - 	SupportedFrameworkVersionRange : [0.0,2147483647.2147483647]
2018-09-08 4:33:19 PM - 
2018-09-08 4:33:19 PM - 	SignatureState     : Unsigned
2018-09-08 4:33:19 PM - 	Supported Products : 
2018-09-08 4:33:19 PM - 		Microsoft.VisualStudio.Code
2018-09-08 4:33:19 PM - 			Version : 
2018-09-08 4:33:19 PM - 
2018-09-08 4:33:19 PM - 	References         : 
2018-09-08 4:33:19 PM - Signature Details...
2018-09-08 4:33:19 PM - 	Extension is not signed.
2018-09-08 4:33:19 PM - 
2018-09-08 4:33:19 PM - Searching for applicable products...
2018-09-08 4:33:19 PM - Found installed product - Global Location
2018-09-08 4:33:19 PM - Found installed product - Visual Studio Community 2017
2018-09-08 4:33:19 PM - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.ExtensionService.GetInstallableData(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionPackService.IsExtensionPack(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.ExtensionPackService.ExpandExtensionPackToInstall(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
```

**Comment by zobo** [comment]
Seems like a local issue. The installer says it only found `Visual Studio` not `Visual Studio Code`. I also never installed the VSIX outside of VS Code, always used the Extensions side bar.
