### ISSUE TITLE
macOS: Can't continue or step over (freeze after first breakpoint)

### ISSUE THREAD

**Issue by binarious** [xdebug/vscode-php-debug#384]
The startup works and the first breakpoint is hit, but then vscode freezes.

Error in vscode:
```
ERR timeout after 500 ms: Error: timeout after 500 ms
    at t.RawDebugSession.handleErrorResponse (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2798:1003)
    at file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2798:434
    at async t.RawDebugSession.shutdown (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2796:536)
    at async R.terminate (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:5173:637)
```

And when clicking one of the debug buttons:
```
ERR no debug adapter found: Error: no debug adapter found
    at t.RawDebugSession.handleErrorResponse (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2798:1003)
    at file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2798:434
    at async t.RawDebugSession.next (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2792:694)
    at async R.next (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:5177:202)
    at async D (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:5103:545)
```

PHP version:  7.3.12 (installed via `brew install php@7.3`)
XDebug version:  v2.9.0 (installed via `pecl install xdebug`)
Adapter version: 1.13.0

Your launch.json:  
```
{
  // Use IntelliSense to learn about possible attributes.
  // Hover to view descriptions of existing attributes.
  // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
  "version": "0.2.0",
  "configurations": [
    {
      "name": "Listen for XDebug",
      "type": "php",
      "request": "launch",
      "log": true,
      "port": 9000
    },
    {
      "name": "Launch currently open script",
      "type": "php",
      "request": "launch",
      "program": "${file}",
      "cwd": "${fileDirname}",
      "port": 9000
    }
  ]
}
```
XDebug php.ini config:
```
zend_extension="xdebug.so"
[XDebug]
xdebug.remote_enable=1
xdebug.remote_autostart=1
xdebug.remote_log = "/tmp/xdebug.log"
```

XDebug logfile (from setting `xdebug.remote_log` in php.ini):  
```
[32831] Log opened at 2019-12-12 07:30:31
[32831] I: Connecting to configured address/port: localhost:9000.
[32831] I: Connected to client. :-)
[32831] -> <init xmlns="urn:debugger_protocol_v1" xmlns:xdebug="https://xdebug.org/dbgp/xdebug" fileuri="file:///Users/myuser/projects/myapp/public/index.php" language="PHP" xdebug:language_version="7.3.12" protocol_version="1.0" appid="32831" idekey="VSCODE"><engine version="2.9.0"><![CDATA[Xdebug]]></engine><author><![CDATA[Derick Rethans]]></author><url><![CDATA[https://xdebug.org]]></url><copyright><![CDATA[Copyright (c) 2002-2019 by Derick Rethans]]></copyright></init>

[32831] <- breakpoint_list -i 1
[32831] -> <response xmlns="urn:debugger_protocol_v1" xmlns:xdebug="https://xdebug.org/dbgp/xdebug" command="breakpoint_list" transaction_id="1"></response>

[32831] <- breakpoint_set -i 2 -t line -f file:///Users/myuser/projects/myapp/public/index.php -n 9
[32831] -> <response xmlns="urn:debugger_protocol_v1" xmlns:xdebug="https://xdebug.org/dbgp/xdebug" command="breakpoint_set" transaction_id="2" id="328310001"></response>

[32831] <- breakpoint_list -i 3
[32831] -> <response xmlns="urn:debugger_protocol_v1" xmlns:xdebug="https://xdebug.org/dbgp/xdebug" command="breakpoint_list" transaction_id="3"><breakpoint type="line" filename="file:///Users/myuser/projects/myapp/public/index.php" lineno="9" state="enabled" hit_count="0" hit_value="0" id="328310001"></breakpoint></response>

[32831] <- breakpoint_list -i 4
[32831] -> <response xmlns="urn:debugger_protocol_v1" xmlns:xdebug="https://xdebug.org/dbgp/xdebug" command="breakpoint_list" transaction_id="4"><breakpoint type="line" filename="file:///Users/myuser/projects/myapp/public/index.php" lineno="9" state="enabled" hit_count="0" hit_value="0" id="328310001"></breakpoint></response>

[32831] <- run -i 5
[32831] -> <response xmlns="urn:debugger_protocol_v1" xmlns:xdebug="https://xdebug.org/dbgp/xdebug" command="run" transaction_id="5" status="break" reason="ok"><xdebug:message filename="file:///Users/myuser/projects/myapp/public/index.php" lineno="9"></xdebug:message></response>

[32831] <- stack_get -i 6
[32831] -> <response xmlns="urn:debugger_protocol_v1" xmlns:xdebug="https://xdebug.org/dbgp/xdebug" command="stack_get" transaction_id="6"><stack where="{main}" level="0" type="file" filename="file:///Users/myuser/projects/myapp/public/index.php" lineno="9"></stack></response>

[33031] Log opened at 2019-12-12 07:30:32
[33031] I: Connecting to configured address/port: localhost:9000.
[33031] I: Connected to client. :-)
[33031] -> <init xmlns="urn:debugger_protocol_v1" xmlns:xdebug="https://xdebug.org/dbgp/xdebug" fileuri="file:///usr/local/Cellar/composer/1.9.1/bin/composer" language="PHP" xdebug:language_version="7.3.12" protocol_version="1.0" appid="33031" idekey="VSCODE"><engine version="2.9.0"><![CDATA[Xdebug]]></engine><author><![CDATA[Derick Rethans]]></author><url><![CDATA[https://xdebug.org]]></url><copyright><![CDATA[Copyright (c) 2002-2019 by Derick Rethans]]></copyright></init>
```

Adapter logfile (from setting `"log": true` in launch.json):
```
<- launchResponse
Response {
  seq: 0,
  type: 'response',
  request_seq: 2,
  command: 'launch',
  success: true
}
new connection 1
<- threadEvent
ThreadEvent {
  seq: 0,
  type: 'event',
  event: 'thread',
  body: { reason: 'started', threadId: 1 }
}
<- initializedEvent
InitializedEvent { seq: 0, type: 'event', event: 'initialized' }
-> setBreakpointsRequest
{
  command: 'setBreakpoints',
  arguments: {
    source: {
      name: 'index.php',
      path: '/Users/myuser/projects/myapp/public/index.php'
    },
    lines: [ 9 ],
    breakpoints: [ { line: 9 } ],
    sourceModified: false
  },
  type: 'request',
  seq: 3
}
<- setBreakpointsResponse
Response {
  seq: 0,
  type: 'response',
  request_seq: 3,
  command: 'setBreakpoints',
  success: true,
  body: { breakpoints: [ { verified: true, line: 9 } ] }
}
-> setFunctionBreakpointsRequest
{
  command: 'setFunctionBreakpoints',
  arguments: { breakpoints: [] },
  type: 'request',
  seq: 4
}
<- setFunctionBreakpointsResponse
Response {
  seq: 0,
  type: 'response',
  request_seq: 4,
  command: 'setFunctionBreakpoints',
  success: true,
  body: { breakpoints: [] }
}
-> setExceptionBreakpointsRequest
{
  command: 'setExceptionBreakpoints',
  arguments: { filters: [] },
  type: 'request',
  seq: 5
}
<- setExceptionBreakpointsResponse
Response {
  seq: 0,
  type: 'response',
  request_seq: 5,
  command: 'setExceptionBreakpoints',
  success: true
}
-> configurationDoneRequest
{ command: 'configurationDone', type: 'request', seq: 6 }
-> threadsRequest
{ command: 'threads', type: 'request', seq: 7 }
<- threadsResponse
Response {
  seq: 0,
  type: 'response',
  request_seq: 7,
  command: 'threads',
  success: true,
  body: { threads: [ Thread { id: 1, name: 'Request 1 (8:30:31 AM)' } ] }
}
<- configurationDoneResponse
Response {
  seq: 0,
  type: 'response',
  request_seq: 6,
  command: 'configurationDone',
  success: true
}
<- stoppedEvent
StoppedEvent {
  seq: 0,
  type: 'event',
  event: 'stopped',
  body: { reason: 'breakpoint', threadId: 1, allThreadsStopped: false }
}
-> threadsRequest
{ command: 'threads', type: 'request', seq: 8 }
<- threadsResponse
Response {
  seq: 0,
  type: 'response',
  request_seq: 8,
  command: 'threads',
  success: true,
  body: { threads: [ Thread { id: 1, name: 'Request 1 (8:30:31 AM)' } ] }
}
-> threadsRequest
{ command: 'threads', type: 'request', seq: 9 }
<- threadsResponse
Response {
  seq: 0,
  type: 'response',
  request_seq: 9,
  command: 'threads',
  success: true,
  body: { threads: [ Thread { id: 1, name: 'Request 1 (8:30:31 AM)' } ] }
}
-> stackTraceRequest
{
  command: 'stackTrace',
  arguments: { threadId: 1, startFrame: 0, levels: 20 },
  type: 'request',
  seq: 10
}
<- stackTraceResponse
Response {
  seq: 0,
  type: 'response',
  request_seq: 10,
  command: 'stackTrace',
  success: true,
  body: {
    stackFrames: [
      {
        id: 1,
        name: '{main}',
        source: {
          name: 'index.php',
          path: '/Users/myuser/projects/myapp/public/index.php'
        },
        line: 9,
        column: 1
      }
    ]
  }
}
```

**Comment by edpittol** [comment]
The same issue here. It all started after I updated the VSCode after a long time.

**Comment by edpittol** [comment]
@binarious Are you using the [PHP Static Analysis](https://github.com/breeze2/vscode-phpstan) extension?

The debug works well when I deactivated this extension.

**Comment by binarious** [comment]
@edpittol Yes, I do. Will check that, thank you.

**Comment by binarious** [comment]
Can confirm. This error only occurs with https://github.com/breeze2/vscode-phpstan being enabled.

**Comment by edpittol** [comment]
A new information that can help.

I ran PHPStan with the debug launched and got this fatal error:

```
PHP Fatal error:  Uncaught _HumbugBox96d25ef69f91\Symfony\Component\Console\Exception\RuntimeException: Too many arguments, expected arguments "command". in phar:///Users/eduardopittol/Sites/php-docker-compose/vendor/phpstan/phpstan/phpstan/vendor/symfony/console/Input/ArgvInput.php:155
Stack trace:
#0 phar:///Users/eduardopittol/Sites/php-docker-compose/vendor/phpstan/phpstan/phpstan/vendor/symfony/console/Input/ArgvInput.php(77): _HumbugBox96d25ef69f91\Symfony\Component\Console\Input\ArgvInput->parseArgument('src/')
#1 phar:///Users/eduardopittol/Sites/php-docker-compose/vendor/phpstan/phpstan/phpstan/vendor/symfony/console/Input/Input.php(50): _HumbugBox96d25ef69f91\Symfony\Component\Console\Input\ArgvInput->parse()
#2 phar:///Users/eduardopittol/Sites/php-docker-compose/vendor/phpstan/phpstan/phpstan/vendor/symfony/console/Application.php(187): _HumbugBox96d25ef69f91\Symfony\Component\Console\Input\Input->bind(Object(_HumbugBox96d25ef69f91\Symfony\Component\Console\Input\InputDefinition))
#3 phar:///Users/eduardopittol/Sit in phar:///Users/eduardopittol/Sites/php-docker-compose/vendor/phpstan/phpstan/phpstan/vendor/symfony/console/Input/ArgvInput.php on line 155
```

**Comment by zobo** [comment]
Seems unrelated to this extension. Closing.
